import bcrypt
from datetime import datetime, timezone, timedelta
from .models import (
    User,
    CrimeReport,
    EmergencyAlert,
    SOSRequest,
    ConsumerComplaint,
    ShopReputation,
    BarcodeVerification,
    AuditLog,
    NotificationItem,
)

def hash_password(password: str) -> str:
    # Generates standard bcrypt hash compatible with bcryptjs demo1234
    salt = bcrypt.gensalt(rounds=8)
    return bcrypt.hashpw(password.encode("utf-8"), salt).decode("utf-8")

def get_seed_records():
    default_hash = hash_password("demo1234")
    now = datetime.now(timezone.utc)

    # 1. Users
    users = [
        User(
            id="user-cit-1",
            nidNumber="19922692015000123",
            fullName="Tanvir Hossain",
            email="citizen.tanvir@example.com",
            phone="+8801711234567",
            role="CITIZEN",
            isNIDVerified=True,
            stationOrThana="Uttara, Dhaka",
            createdAt=(now - timedelta(days=60)).isoformat(),
            passwordHash=default_hash,
        ),
        User(
            id="user-cit-2",
            nidNumber="5508192841",
            fullName="Farhana Sultana",
            email="farhana.s@example.com",
            phone="+8801819876543",
            role="CITIZEN",
            isNIDVerified=True,
            stationOrThana="Panchlaish, Chattogram",
            createdAt=(now - timedelta(days=45)).isoformat(),
            passwordHash=default_hash,
        ),
        User(
            id="user-pol-1",
            nidNumber="1098472918",
            fullName="Inspector Kamrul Islam",
            email="police.kamrul@dmp.gov.bd",
            phone="+8801713001122",
            role="POLICE",
            badgeNumber="DMP-84920",
            designation="Officer-in-Charge (OC)",
            department="Dhaka Metropolitan Police - Crime Division",
            stationOrThana="Gulshan Thana, Dhaka",
            isNIDVerified=True,
            createdAt=(now - timedelta(days=120)).isoformat(),
            passwordHash=default_hash,
        ),
        User(
            id="user-pol-2",
            nidNumber="2948103948",
            fullName="SI Nazmul Huda",
            email="nazmul.huda@cmp.gov.bd",
            phone="+8801713009988",
            role="POLICE",
            badgeNumber="CMP-31409",
            designation="Sub-Inspector",
            department="Chattogram Metropolitan Police",
            stationOrThana="Agrabad / Kotwali, Chattogram",
            isNIDVerified=True,
            createdAt=(now - timedelta(days=110)).isoformat(),
            passwordHash=default_hash,
        ),
        User(
            id="user-pol-3",
            nidNumber="1849204918",
            fullName="SI Faruq Ahmed",
            email="faruq.ahmed@dmp.gov.bd",
            phone="+8801713007766",
            role="POLICE",
            badgeNumber="DMP-44120",
            designation="Sub-Inspector",
            department="Dhaka Metropolitan Police - Crime Division",
            stationOrThana="Gulshan Thana, Dhaka",
            isNIDVerified=True,
            createdAt=(now - timedelta(days=100)).isoformat(),
            passwordHash=default_hash,
        ),
        User(
            id="user-cr-1",
            nidNumber="3948102948",
            fullName="Shamim Reza",
            email="shamim.reza@dncrp.gov.bd",
            phone="+8801712884433",
            role="CONSUMER_RIGHTS",
            badgeNumber="DNCRP-OFFICER-44",
            designation="Deputy Director (Enforcement & Vigilance)",
            department="Directorate of National Consumers Right Protection (DNCRP)",
            stationOrThana="Dhaka Central Directorate",
            isNIDVerified=True,
            createdAt=(now - timedelta(days=90)).isoformat(),
            passwordHash=default_hash,
        ),
        User(
            id="user-adm-1",
            nidNumber="19800029381928371",
            fullName="Dr. Tariqul Alam",
            email="admin@sentinelx.gov.bd",
            phone="+8801710000001",
            role="ADMIN",
            badgeNumber="ADMIN-SYS-001",
            designation="Chief Information & Security Officer",
            department="National Cyber Security & Public Safety Commission",
            stationOrThana="Central Command HQ, Dhaka",
            isNIDVerified=True,
            createdAt=(now - timedelta(days=365)).isoformat(),
            passwordHash=default_hash,
        ),
    ]

    # 2. Crime Reports (including verified incidents for police heatmap)
    reports = [
        CrimeReport(
            id="rep-001",
            caseId="CR-DHK-2026-0814",
            reporterId="user-cit-1",
            reporterName="Tanvir Hossain",
            reporterPhone="+8801711234567",
            reporterNID="19922692015000123",
            requestConfidentiality=True,
            crimeType="THEFT_ROBBERY",
            title="Armed snatching incident near Gulshan 2 roundabout",
            description="Two perpetrators on an unnumbered motorcycle intercepted pedestrian carrying cash bag containing BDT 1,20,000 withdrawn from nearby commercial bank. They brandished sharp weapons and fled toward Kamal Ataturk Ave.",
            locationName="Gulshan 2, Near Landmark Tower",
            district="Dhaka",
            thana="Gulshan",
            latitude=23.7925,
            longitude=90.4078,
            occurredAt=(now - timedelta(days=5, hours=2)).isoformat(),
            submittedAt=(now - timedelta(days=5)).isoformat(),
            severity="HIGH",
            status="INVESTIGATION",
            evidence=[{
                "id": "ev-1",
                "fileName": "cctv_screenshot_snatching.jpg",
                "fileType": "image",
                "fileUrl": "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80",
                "fileSize": "1.4 MB",
                "uploadedAt": (now - timedelta(days=5)).isoformat()
            }],
            verificationNotes="Verified via physical visit and CCTV footage from Gulshan Shopping Centre camera 4.",
            verifiedByOfficerId="user-pol-1",
            assignedOfficerId="user-pol-1",
            assignedOfficerName="Inspector Kamrul Islam",
            assignedOfficerBadge="DMP-84920",
            assignedOfficerStation="Gulshan Thana, DMP",
            investigationUpdates=[
                {
                    "id": "inv-1",
                    "timestamp": (now - timedelta(days=4, hours=8)).isoformat(),
                    "officerName": "Inspector Kamrul Islam",
                    "status": "VERIFIED",
                    "note": "Preliminary verification completed. Incident confirmed with physical evidence."
                },
                {
                    "id": "inv-2",
                    "timestamp": (now - timedelta(days=3)).isoformat(),
                    "officerName": "Inspector Kamrul Islam",
                    "status": "OFFICER_ASSIGNED",
                    "note": "Case assigned to Sub-Inspector Al-Amin for motorcycle registration cross-check."
                },
                {
                    "id": "inv-3",
                    "timestamp": (now - timedelta(days=2)).isoformat(),
                    "officerName": "Inspector Kamrul Islam",
                    "status": "INVESTIGATION",
                    "note": "Suspect motorcycle tracked on Banani bridge surveillance camera."
                }
            ]
        ),
        CrimeReport(
            id="rep-002",
            caseId="CR-DHK-2026-0820",
            reporterId="user-cit-1",
            reporterName="Tanvir Hossain",
            reporterPhone="+8801711234567",
            reporterNID="19922692015000123",
            requestConfidentiality=False,
            crimeType="CYBER_CRIME",
            title="Mobile Financial Service (MFS) OTP Phishing scam",
            description="Impersonator called claiming to be bKash security officer and tricked store clerk into sharing PIN code, transferring BDT 45,000 fraudulently.",
            locationName="Sector 4, Uttara, Dhaka",
            district="Dhaka",
            thana="Uttara",
            latitude=23.8759,
            longitude=90.3795,
            occurredAt=(now - timedelta(days=4, hours=10)).isoformat(),
            submittedAt=(now - timedelta(days=4, hours=9)).isoformat(),
            severity="MEDIUM",
            status="VERIFIED",
            evidence=[{
                "id": "ev-2",
                "fileName": "sms_transaction_receipt.png",
                "fileType": "image",
                "fileUrl": "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80",
                "fileSize": "480 KB",
                "uploadedAt": (now - timedelta(days=4, hours=9)).isoformat()
            }],
            verificationNotes="MFS transaction ID verified with bKash Bangladesh cyber liaison unit.",
            verifiedByOfficerId="user-pol-1",
            assignedOfficerName="Inspector Kamrul Islam",
            investigationUpdates=[{
                "id": "inv-4",
                "timestamp": (now - timedelta(days=3)).isoformat(),
                "officerName": "Inspector Kamrul Islam",
                "status": "VERIFIED",
                "note": "Verification approved. Forwarded to Cyber Crime Division for IP/SIM lock."
            }]
        ),
        CrimeReport(
            id="rep-003",
            caseId="CR-CTG-2026-0855",
            reporterId="user-cit-2",
            reporterName="Farhana Sultana",
            reporterPhone="+8801819876543",
            reporterNID="5508192841",
            requestConfidentiality=True,
            crimeType="EXTORTION",
            title="Extortion and intimidation at local wholesale trading shop",
            description="Local syndicate demanding monthly illegal levy of BDT 20,000 from grocery distributor under threat of shop disruption.",
            locationName="GEC Circle, Nasirabad, Chattogram",
            district="Chattogram",
            thana="Panchlaish",
            latitude=22.3590,
            longitude=91.8215,
            occurredAt=(now - timedelta(days=6)).isoformat(),
            submittedAt=(now - timedelta(days=6, hours=-2)).isoformat(),
            severity="HIGH",
            status="SUBMITTED",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="rep-004",
            caseId="CR-DHK-2026-0901",
            reporterId="user-cit-2",
            reporterName="Farhana Sultana",
            reporterPhone="+8801819876543",
            reporterNID="5508192841",
            requestConfidentiality=False,
            crimeType="HARASSMENT",
            title="Eve-teasing and aggressive stalking near Mirpur Girls College",
            description="Repeated stalking and offensive verbal abuse directed at female students during college departure hours.",
            locationName="Mirpur Section 2, Dhaka",
            district="Dhaka",
            thana="Mirpur",
            latitude=23.8071,
            longitude=90.3686,
            occurredAt=(now - timedelta(days=7)).isoformat(),
            submittedAt=(now - timedelta(days=7, hours=-1)).isoformat(),
            severity="MEDIUM",
            status="CASE_CLOSED",
            evidence=[],
            verificationNotes="Community police dispatched. Culprits apprehended and warning executed with parental bond.",
            verifiedByOfficerId="user-pol-1",
            assignedOfficerName="Inspector Kamrul Islam",
            investigationUpdates=[
                {
                    "id": "inv-5",
                    "timestamp": (now - timedelta(days=7)).isoformat(),
                    "officerName": "Inspector Kamrul Islam",
                    "status": "VERIFIED",
                    "note": "College administration statement recorded."
                },
                {
                    "id": "inv-6",
                    "timestamp": (now - timedelta(days=6)).isoformat(),
                    "officerName": "Inspector Kamrul Islam",
                    "status": "CASE_CLOSED",
                    "note": "Resolved via Mobile Court action and strict patrolling guarantee."
                }
            ]
        ),
        CrimeReport(
            id="rep-005",
            caseId="CR-DHK-2026-0942",
            reporterId="user-cit-1",
            reporterName="Tanvir Hossain",
            reporterPhone="+8801711234567",
            reporterNID="19922692015000123",
            requestConfidentiality=False,
            crimeType="THEFT_ROBBERY",
            title="Commercial store break-in attempt near Gulshan Avenue",
            description="Attempted forced entry at electronic appliance showroom during late night hours. Shutter lock damaged before patrol siren frightened perpetrators away.",
            locationName="Road 11, Gulshan 1, Dhaka",
            district="Dhaka",
            thana="Gulshan",
            latitude=23.7808,
            longitude=90.4192,
            occurredAt=(now - timedelta(hours=8)).isoformat(),
            submittedAt=(now - timedelta(hours=6)).isoformat(),
            severity="MEDIUM",
            status="SUBMITTED",
            evidence=[],
            investigationUpdates=[]
        ),
        # Incidents for verified police heatmap
        CrimeReport(
            id="inc-01",
            caseId="INC-DHK-GUL-01",
            reporterId="user-cit-1",
            reporterName="Verified Reporter",
            reporterPhone="+8801700000000",
            reporterNID="1000000001",
            requestConfidentiality=False,
            crimeType="THEFT_ROBBERY",
            title="Vehicle break-in at Kemal Ataturk Ave",
            description="Laptop and documents stolen from parked private car.",
            locationName="Banani 11, Dhaka",
            district="Dhaka",
            thana="Banani",
            latitude=23.7937,
            longitude=90.4043,
            occurredAt=(now - timedelta(days=10)).isoformat(),
            submittedAt=(now - timedelta(days=10)).isoformat(),
            severity="HIGH",
            status="VERIFIED",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="inc-02",
            caseId="INC-DHK-MIR-02",
            reporterId="user-cit-1",
            reporterName="Verified Reporter",
            reporterPhone="+8801700000000",
            reporterNID="1000000002",
            requestConfidentiality=False,
            crimeType="THEFT_ROBBERY",
            title="Pickpocketing cluster near Mirpur 10 Metro Station",
            description="Multiple wallet snatching incidents reported during rush hour.",
            locationName="Mirpur 10 Roundabout",
            district="Dhaka",
            thana="Mirpur",
            latitude=23.8069,
            longitude=90.3687,
            occurredAt=(now - timedelta(days=9)).isoformat(),
            submittedAt=(now - timedelta(days=9)).isoformat(),
            severity="MEDIUM",
            status="INVESTIGATION",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="inc-03",
            caseId="INC-DHK-DHA-03",
            reporterId="user-cit-1",
            reporterName="Verified Reporter",
            reporterPhone="+8801700000000",
            reporterNID="1000000003",
            requestConfidentiality=False,
            crimeType="FRAUD_SCAM",
            title="Fake Job Agency Scam at Dhanmondi 27",
            description="Unlicensed agency collecting fake visa processing fees.",
            locationName="Dhanmondi 27, Dhaka",
            district="Dhaka",
            thana="Dhanmondi",
            latitude=23.7538,
            longitude=90.3756,
            occurredAt=(now - timedelta(days=12)).isoformat(),
            submittedAt=(now - timedelta(days=12)).isoformat(),
            severity="HIGH",
            status="CASE_CLOSED",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="inc-04",
            caseId="INC-DHK-MOT-04",
            reporterId="user-cit-1",
            reporterName="Verified Reporter",
            reporterPhone="+8801700000000",
            reporterNID="1000000004",
            requestConfidentiality=False,
            crimeType="DRUG_TRAFFICKING",
            title="Yaba tablets consignment seized at Kamalapur Railway area",
            description="Inter-district drug syndicate consignment intercepted by joint patrol.",
            locationName="Kamalapur Station, Motijheel",
            district="Dhaka",
            thana="Motijheel",
            latitude=23.7314,
            longitude=90.4253,
            occurredAt=(now - timedelta(days=8)).isoformat(),
            submittedAt=(now - timedelta(days=8)).isoformat(),
            severity="CRITICAL",
            status="INVESTIGATION",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="inc-05",
            caseId="INC-CTG-AGR-05",
            reporterId="user-cit-2",
            reporterName="Verified Reporter",
            reporterPhone="+8801800000000",
            reporterNID="1000000005",
            requestConfidentiality=False,
            crimeType="EXTORTION",
            title="Transport extortion at Badamtali intersection",
            description="Truck drivers harassed for unauthorized parking fees.",
            locationName="Agrabad Commercial Area, Chattogram",
            district="Chattogram",
            thana="Agrabad",
            latitude=22.3275,
            longitude=91.8122,
            occurredAt=(now - timedelta(days=7)).isoformat(),
            submittedAt=(now - timedelta(days=7)).isoformat(),
            severity="HIGH",
            status="VERIFIED",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="inc-06",
            caseId="INC-CTG-KOT-06",
            reporterId="user-cit-2",
            reporterName="Verified Reporter",
            reporterPhone="+8801800000000",
            reporterNID="1000000006",
            requestConfidentiality=False,
            crimeType="THEFT_ROBBERY",
            title="Jewelry shop burglary attempt at New Market",
            description="Lock-cutting tools seized after alarm system triggered.",
            locationName="Kotwali, Chattogram New Market",
            district="Chattogram",
            thana="Kotwali",
            latitude=22.3350,
            longitude=91.8325,
            occurredAt=(now - timedelta(days=4)).isoformat(),
            submittedAt=(now - timedelta(days=4)).isoformat(),
            severity="CRITICAL",
            status="INVESTIGATION",
            evidence=[],
            investigationUpdates=[]
        ),
        CrimeReport(
            id="inc-07",
            caseId="INC-SYL-ZIN-07",
            reporterId="user-cit-1",
            reporterName="Verified Reporter",
            reporterPhone="+8801700000000",
            reporterNID="1000000007",
            requestConfidentiality=False,
            crimeType="HARASSMENT",
            title="Harassment reported near City Centre Plaza",
            description="Verified incident with disciplinary action taken.",
            locationName="Zindabazar, Sylhet",
            district="Sylhet",
            thana="Kotwali",
            latitude=24.8949,
            longitude=91.8687,
            occurredAt=(now - timedelta(days=11)).isoformat(),
            submittedAt=(now - timedelta(days=11)).isoformat(),
            severity="LOW",
            status="CASE_CLOSED",
            evidence=[],
            investigationUpdates=[]
        )
    ]

    # 3. Emergency Alerts
    alerts = [
        EmergencyAlert(
            id="alert-001",
            alertCode="ALERT-DHK-FIRE-01",
            emergencyType="MAJOR_FIRE",
            title="Major Chemical Warehouse Fire Hazard - Evacuation Advisory",
            message="A significant industrial fire broke out near Tejgaon Industrial Area Block B. Severe toxic smoke plume spreading toward Mohakhali and Nakhalpara. Fire Service & Civil Defence units are active on site. Citizens are advised to close windows, wear masks, and avoid the Shaheed Tajuddin Ahmad Sarani corridor.",
            affectedArea="Tejgaon Industrial Area & Mohakhali, Dhaka",
            district="Dhaka",
            latitude=23.7685,
            longitude=90.3980,
            radiusKm=3.5,
            severity="CRITICAL",
            issuedByOfficerId="user-pol-1",
            issuedByOfficerName="Inspector Kamrul Islam",
            issuedByStation="Tejgaon / Gulshan Command, DMP",
            startTime=(now - timedelta(hours=3)).isoformat(),
            expirationTime=(now + timedelta(hours=6)).isoformat(),
            isActive=True,
            createdAt=(now - timedelta(hours=3)).isoformat(),
        ),
        EmergencyAlert(
            id="alert-002",
            alertCode="ALERT-CTG-WEATHER-02",
            emergencyType="WEATHER_HAZARD",
            title="Severe Coastal Tidal Surge & Flash Flood Warning",
            message="Meteorological Dept issues Signal 7 for Chittagong Port. High astronomical tide combined with deep depression may inundate low-lying areas of Halishahar, Patenga, and Agrabad. Emergency shelter centers activated.",
            affectedArea="Patenga & Halishahar Coastal Belt, Chattogram",
            district="Chattogram",
            latitude=22.2500,
            longitude=91.8000,
            radiusKm=12.0,
            severity="HIGH",
            issuedByOfficerId="user-pol-2",
            issuedByOfficerName="SI Nazmul Huda",
            issuedByStation="CMP Coastal Security Command",
            startTime=(now - timedelta(hours=12)).isoformat(),
            expirationTime=(now + timedelta(hours=18)).isoformat(),
            isActive=True,
            createdAt=(now - timedelta(hours=12)).isoformat(),
        ),
    ]

    # 4. SOS Requests
    sos_requests = [
        SOSRequest(
            id="sos-001",
            citizenId="user-cit-1",
            citizenName="Tanvir Hossain",
            citizenPhone="+8801711234567",
            citizenNID="19922692015000123",
            locationName="Near Jasimuddin Road, Uttara Sector 3, Dhaka",
            latitude=23.8680,
            longitude=90.3950,
            status="RESPONDING",
            createdAt=(now - timedelta(minutes=25)).isoformat(),
            respondedAt=(now - timedelta(minutes=20)).isoformat(),
            assignedUnit="DMP Mobile Patrol Van 14 (Uttara East)",
            notes="Officer contacted citizen via phone; patrol vehicle arrived at location.",
        )
    ]

    # 5. Consumer Complaints
    complaints = [
        ConsumerComplaint(
            id="comp-001",
            trackingNumber="DNCRP-DHK-2026-1049",
            complainantId="user-cit-1",
            complainantName="Tanvir Hossain",
            complainantPhone="+8801711234567",
            shopName="Al-Madina Super Store",
            shopAddress="Plot 12, Main Road, Uttara Sector 6, Dhaka",
            shopDistrict="Dhaka",
            shopThana="Uttara",
            tradeLicenseOrBIN="BIN-948201948",
            productName="Imported Baby Milk Formula (900g)",
            brandName="NutriGrow Stage 2",
            barcode="8901030491024",
            batchNumber="BATCH-NG-889",
            issueType="PRICE_GOUGING",
            pricePaid=2450.0,
            mrp=1850.0,
            description="The store charged BDT 2,450 for a baby milk tin with printed government Maximum Retail Price (MRP) of BDT 1,850. Merchant altered price sticker with manual marker.",
            submittedAt=(now - timedelta(days=3)).isoformat(),
            status="INVESTIGATION",
            evidence=[{
                "id": "ev-comp-1",
                "fileName": "cash_memo_overcharging.jpg",
                "fileType": "image",
                "fileUrl": "https://images.unsplash.com/photo-1554415707-9e49016a3b63?auto=format&fit=crop&w=600&q=80",
                "fileSize": "890 KB",
                "uploadedAt": (now - timedelta(days=3)).isoformat()
            }],
            inspectorNotes="DNCRP inspection team conducted physical audit. Found 42 units of tampering with MRP. Notice served under Consumer Rights Protection Act 2009 Section 40.",
            penaltyImposed="Show-cause notice issued with penalty assessment of BDT 50,000.",
            assignedOfficerName="Shamim Reza",
            timeline=[
                {"timestamp": (now - timedelta(days=3)).isoformat(), "status": "SUBMITTED", "note": "Complaint registered by citizen with purchase receipt."},
                {"timestamp": (now - timedelta(days=2)).isoformat(), "status": "UNDER_REVIEW", "note": "Initial scrutiny confirmed evidence meets legal threshold.", "officerName": "Shamim Reza"},
                {"timestamp": (now - timedelta(days=1)).isoformat(), "status": "VERIFIED", "note": "Physical raid on merchant premises confirmed violations.", "officerName": "Shamim Reza"},
                {"timestamp": now.isoformat(), "status": "INVESTIGATION", "note": "Formal inquiry hearing scheduled under DNCRP rules.", "officerName": "Shamim Reza"}
            ]
        ),
        ConsumerComplaint(
            id="comp-002",
            trackingNumber="DNCRP-CTG-2026-0422",
            complainantId="user-cit-2",
            complainantName="Farhana Sultana",
            complainantPhone="+8801819876543",
            shopName="Green Life Pharmacy & Surgicals",
            shopAddress="Chawkbazar Circle, Chattogram",
            shopDistrict="Chattogram",
            shopThana="Kotwali",
            tradeLicenseOrBIN="BIN-110294829",
            productName="Paracetamol 500mg (100 Tablets Box)",
            brandName="Napa Extend",
            barcode="8941100349281",
            issueType="EXPIRED_GOODS",
            pricePaid=120.0,
            mrp=120.0,
            description="Sold expired medication with scratch-off expiration date stamp.",
            submittedAt=(now - timedelta(days=8)).isoformat(),
            status="RESOLVED",
            evidence=[],
            inspectorNotes="Mobile court fine of BDT 30,000 imposed. Expired stock confiscated and destroyed in presence of Magistrate. Citizen awarded 25% fine incentive (BDT 7,500) per DNCRP Act Section 76(4).",
            penaltyImposed="BDT 30,000 Administrative Fine + 25% reward disbursed to complainant.",
            assignedOfficerName="Shamim Reza",
            timeline=[
                {"timestamp": (now - timedelta(days=8)).isoformat(), "status": "SUBMITTED", "note": "Complaint submitted with product batch photograph."},
                {"timestamp": (now - timedelta(days=6)).isoformat(), "status": "VERIFIED", "note": "Directorate inspectors verified expired lot numbers.", "officerName": "Shamim Reza"},
                {"timestamp": (now - timedelta(days=4)).isoformat(), "status": "RESOLVED", "note": "Case resolved. Fine deposited and incentive paid to citizen.", "officerName": "Shamim Reza"}
            ]
        )
    ]

    # 6. Shops
    shops = [
        ShopReputation(
            id="shop-01",
            shopName="Al-Madina Super Store",
            tradeLicenseOrBIN="BIN-948201948",
            address="Plot 12, Main Road, Uttara Sector 6, Dhaka",
            district="Dhaka",
            thana="Uttara",
            category="Grocery & Departmental",
            trustScore=2.8,
            totalComplaints=4,
            resolvedComplaints=3,
            verifiedFinesCount=2,
            lastInspectedAt=(now - timedelta(days=2)).isoformat(),
            complianceStatus="UNDER_WATCH",
        ),
        ShopReputation(
            id="shop-02",
            shopName="Shwapno Super Shop (Gulshan 1 Branch)",
            tradeLicenseOrBIN="BIN-839201847",
            address="Gulshan 1 DIT Market, Dhaka",
            district="Dhaka",
            thana="Gulshan",
            category="Superstore Chain",
            trustScore=4.8,
            totalComplaints=2,
            resolvedComplaints=2,
            verifiedFinesCount=0,
            lastInspectedAt=(now - timedelta(days=14)).isoformat(),
            complianceStatus="EXEMPLARY",
        ),
        ShopReputation(
            id="shop-03",
            shopName="Green Life Pharmacy & Surgicals",
            tradeLicenseOrBIN="BIN-110294829",
            address="Chawkbazar Circle, Chattogram",
            district="Chattogram",
            thana="Kotwali",
            category="Pharmacy & Healthcare",
            trustScore=3.2,
            totalComplaints=3,
            resolvedComplaints=3,
            verifiedFinesCount=1,
            lastInspectedAt=(now - timedelta(days=4)).isoformat(),
            complianceStatus="GOOD",
        ),
        ShopReputation(
            id="shop-04",
            shopName="Bengal Pure Oil Mills",
            tradeLicenseOrBIN="BIN-449102948",
            address="Khatunganj Wholesale Market, Chattogram",
            district="Chattogram",
            thana="Kotwali",
            category="Edible Oils & Commodities",
            trustScore=1.6,
            totalComplaints=7,
            resolvedComplaints=2,
            verifiedFinesCount=4,
            lastInspectedAt=(now - timedelta(days=20)).isoformat(),
            complianceStatus="SUSPENDED",
        ),
    ]

    # 7. Barcodes (BSTI verified catalog)
    barcodes = [
        BarcodeVerification(
            barcode="8901030491024",
            productName="NutriGrow Stage 2 Baby Formula (900g)",
            companyName="Apex Nutrition BD Ltd",
            bstiStandard="BDS-CAC-72:2018",
            mrp=1850.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8941100349281",
            productName="Napa Extend 665mg (Box of 120)",
            companyName="Beximco Pharmaceuticals Ltd",
            bstiStandard="DGDA-REG-014-049",
            mrp=240.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8941100001029",
            productName="Radhuni Pure Mustard Oil (1 Litre)",
            companyName="Square Consumer Products Ltd",
            bstiStandard="BDS 427:2019 (BSTI Verified)",
            mrp=320.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8941100234012",
            productName="Teer Fortified Soybean Oil 1 Litre",
            companyName="City Edible Oil Ltd, Narayanganj",
            bstiStandard="BDS 1769:2014",
            mrp=175.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8941100456123",
            productName="Fresh Refined Sugar 1 Kg Pack",
            companyName="Meghna Sugar Refinery Ltd",
            bstiStandard="BDS 138:2006",
            mrp=135.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8941100998811",
            productName="Aarong Dairy Pasteurized Liquid Milk 500ml",
            companyName="BRAC Dairy & Food Project, Gazipur",
            bstiStandard="BDS 860:2001",
            mrp=50.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8941100778899",
            productName="Ispahani Mirzapore Best Blend Tea 400g",
            companyName="Ispahani Foods Ltd, Chattogram",
            bstiStandard="BDS 1586:2007",
            mrp=220.0,
            isRegistered=True,
            status="AUTHENTIC",
        ),
        BarcodeVerification(
            barcode="8900000999999",
            productName="Counterfeit Foreign Cosmetics Lot",
            companyName="Unregistered Entity",
            bstiStandard="NONE (Flagged by Customs)",
            mrp=1500.0,
            isRegistered=False,
            status="COUNTERFEIT_FLAGGED",
        ),
    ]

    # 8. Audit Logs
    audit_logs = [
        AuditLog(
            id="audit-001",
            timestamp=(now - timedelta(days=1)).isoformat(),
            userId="user-adm-1",
            userName="Dr. Tariqul Alam",
            userRole="ADMIN",
            action="SYSTEM_BOOTSTRAP",
            resource="PLATFORM_CORE",
            ipAddress="10.0.4.12",
            status="SUCCESS",
            details="SentinelX National Public Safety & Consumer Protection Engine initialized with PostgreSQL relational storage.",
        ),
        AuditLog(
            id="audit-002",
            timestamp=(now - timedelta(hours=10)).isoformat(),
            userId="user-pol-1",
            userName="Inspector Kamrul Islam",
            userRole="POLICE",
            action="VERIFY_CRIME_REPORT",
            resource="CR-DHK-2026-0814",
            resourceId="rep-001",
            ipAddress="103.14.88.22",
            status="SUCCESS",
            details="Officer verified snatching incident; reporter confidentiality flag protected.",
        ),
        AuditLog(
            id="audit-003",
            timestamp=(now - timedelta(hours=3)).isoformat(),
            userId="user-pol-1",
            userName="Inspector Kamrul Islam",
            userRole="POLICE",
            action="PUBLISH_EMERGENCY_ALERT",
            resource="ALERT-DHK-FIRE-01",
            resourceId="alert-001",
            ipAddress="103.14.88.22",
            status="SUCCESS",
            details="Emergency Alert [MAJOR_FIRE] published for [Tejgaon Industrial Area & Mohakhali, Dhaka].",
        ),
    ]

    return {
        "users": users,
        "reports": reports,
        "alerts": alerts,
        "sos_requests": sos_requests,
        "complaints": complaints,
        "shops": shops,
        "barcodes": barcodes,
        "audit_logs": audit_logs,
    }
